name: CI

on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

# fake env variables to bypass env check
env: 
  NEXT_PUBLIC_APP_URL: "https://duskyworld.vercel.app/"
  NEXT_PUBLIC_TMDB_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyZjBhNTM0NTFlNTEwYTcyMjk4NTdjODYwODcxN2VmYyIsIm5iZiI6MTcyOTY4MzU3Mi45ODY5NDcsInN1YiI6IjY2Yzk2ZmExOGNkMTMxMjI1YTJkNDYxNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Pv75-aIEXVNSU4k52-9JtyqsxJoFAdR4z4Omb-aPuPM"
  NEXT_PUBLIC_SITE_NAME: "Duskyworld"
  NEXT_PUBLIC_IMAGE_DOMAIN: "https://duskyworld.vercel.app/"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
